### PR TITLE
Fix for search select component

### PR DESCRIPTION
**Pull request by iamtomcat**
Hey this is a fix for #51 as we needed this to work. Pretty simple fix, just had to change the setup to a later life cycle function.

### CODE REVIEW

**Comment by TryHardDood** [comment]
Thanks! :)

**Comment by iamtomcat** [comment]
No worries. Glad I could help.

**Comment by iamtomcat** [comment]
Also @TryHardDood are you going to publish a new version soon or is there something you're waiting on?

**Comment by Kitcheone** [comment]
I'd also love a new version to be published that contains this fix. Is there any chance of a new version soon?

**Comment by TryHardDood** [comment]
Sure thing, I'll publish a version with this fix tomorrow

**Comment by Kitcheone** [comment]
That's awesome, thanks!

**Comment by TryHardDood** [comment]
@Kitcheone @iamtomcat Published with v0.11.6

I'm working on a version to make this library work with Angular 10.

**Comment by Kitcheone** [comment]
Thanks so much @TryHardDood ! An Angular 10 version would be super sweet for my current project too!

**Comment by iamtomcat** [comment]
Thanks for the release @TryHardDood !

**Pull request merged**
